# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monoGUI2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 551)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(478, 400, 211, 41))
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 130, 631, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TexBox1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.TexBox1.setObjectName("TexBox1")
        self.horizontalLayout.addWidget(self.TexBox1)
        self.pickNM = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.pickNM.setDecimals(2)
        self.pickNM.setMinimum(350.0)
        self.pickNM.setMaximum(2500.0)
        self.pickNM.setProperty("value", 700.0)
        self.pickNM.setObjectName("pickNM")
        self.horizontalLayout.addWidget(self.pickNM)
        self.gotoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.gotoButton.setObjectName("gotoButton")
        self.horizontalLayout.addWidget(self.gotoButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 40, 631, 82))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TextBox5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.TextBox5.setObjectName("TextBox5")
        self.horizontalLayout_2.addWidget(self.TextBox5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Blaze_300 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.Blaze_300.setObjectName("Blaze_300")
        self.verticalLayout.addWidget(self.Blaze_300)
        self.Blaze_750 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.Blaze_750.setObjectName("Blaze_750")
        self.verticalLayout.addWidget(self.Blaze_750)
        self.Blaze_1600 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.Blaze_1600.setObjectName("Blaze_1600")
        self.verticalLayout.addWidget(self.Blaze_1600)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gratingButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.gratingButton.setObjectName("gratingButton")
        self.horizontalLayout_2.addWidget(self.gratingButton)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 200, 631, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextBox2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TextBox2.setLineWidth(1)
        self.TextBox2.setTextFormat(QtCore.Qt.AutoText)
        self.TextBox2.setObjectName("TextBox2")
        self.gridLayout_2.addWidget(self.TextBox2, 0, 0, 1, 1)
        self.StartNM = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.StartNM.setMinimum(350.0)
        self.StartNM.setMaximum(2500.0)
        self.StartNM.setObjectName("StartNM")
        self.gridLayout_2.addWidget(self.StartNM, 0, 1, 1, 1)
        self.TextBox4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TextBox4.setObjectName("TextBox4")
        self.gridLayout_2.addWidget(self.TextBox4, 2, 0, 1, 1)
        self.StopNM = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.StopNM.setMinimum(350.0)
        self.StopNM.setMaximum(2500.0)
        self.StopNM.setProperty("value", 2500.0)
        self.StopNM.setObjectName("StopNM")
        self.gridLayout_2.addWidget(self.StopNM, 1, 1, 1, 1)
        self.ScanSpeed = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.ScanSpeed.setDecimals(2)
        self.ScanSpeed.setMinimum(0.01)
        self.ScanSpeed.setMaximum(2500.0)
        self.ScanSpeed.setProperty("value", 1000.0)
        self.ScanSpeed.setObjectName("ScanSpeed")
        self.gridLayout_2.addWidget(self.ScanSpeed, 2, 1, 1, 1)
        self.TextBox3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TextBox3.setObjectName("TextBox3")
        self.gridLayout_2.addWidget(self.TextBox3, 1, 0, 1, 1)
        self.scanButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.scanButton.setObjectName("scanButton")
        self.gridLayout_2.addWidget(self.scanButton, 2, 2, 1, 1)
        self.connectButton.raise_()
        self.horizontalLayoutWidget.raise_()
        self.TextBox5.raise_()
        self.TexBox1.raise_()
        self.TextBox5.raise_()
        self.TexBox1.raise_()
        self.TexBox1.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.gridLayoutWidget_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.TexBox1.setText(_translate("MainWindow", "Select Wavelength :"))
        self.pickNM.setSuffix(_translate("MainWindow", " [nm]"))
        self.gotoButton.setText(_translate("MainWindow", "GOTO"))
        self.TextBox5.setText(_translate("MainWindow", "Select Grating :"))
        self.Blaze_300.setText(_translate("MainWindow", "300 nm Blaze Wavelength"))
        self.Blaze_750.setText(_translate("MainWindow", "750 nm Blaze Wavelength"))
        self.Blaze_1600.setText(_translate("MainWindow", "1600 nm Blaze Wavelength"))
        self.gratingButton.setText(_translate("MainWindow", "Update"))
        self.TextBox2.setText(_translate("MainWindow", "Start :"))
        self.StartNM.setSuffix(_translate("MainWindow", " [nm]"))
        self.TextBox4.setText(_translate("MainWindow", "Scan Speed :"))
        self.StopNM.setSuffix(_translate("MainWindow", " [nm]"))
        self.ScanSpeed.setSuffix(_translate("MainWindow", " [nm/min]"))
        self.TextBox3.setText(_translate("MainWindow", "Stop :"))
        self.scanButton.setText(_translate("MainWindow", "Scan"))

